### PR TITLE
Logons Listing

### PR DESCRIPTION
**Pull request by ShrikantWinapps**
Logon Listing (23/4/2021)

### CODE REVIEW

**Comment by BalvinderWinapps** [comment]
Done

**Comment by ShrikantWinapps** [comment]
Pages Developed 

Individual Cost Centers
SetupData/LogonCostCenter
Product Search
ServiceContracts/ViewContracts

**Comment by ShrikantWinapps** [comment]
System management with some new pages developed

**Comment by BalvinderWinapps** [comment]
Done

**Comment by ShrikantWinapps** [comment]
FaoriteDesign Pull Request

**Pull request merged**
